/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eppo_EppoClient */

#ifndef _Included_com_eppo_EppoClient
#define _Included_com_eppo_EppoClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eppo_EppoClient
 * Method:    getStringAssignment
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eppo_EppoClient_getStringAssignment
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
