# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
require_relative 'lib/eppo_client/version'

GEM_NAME = 'eppo-server-sdk'
GEM_VERSION = EppoClient::VERSION

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "rb_sys/extensiontask"

task default: :build

GEMSPEC = Gem::Specification.load("eppo-server-sdk.gemspec")

RbSys::ExtensionTask.new("eppo_client", GEMSPEC) do |ext|
  ext.lib_dir = "lib/eppo_client"
end

task build: :compile do
  system "gem build #{GEM_NAME}.gemspec"
end

task install: :build do
  system "gem install #{GEM_NAME}-#{GEM_VERSION}.gem"
end

task devinstall: :build do
  system "gem install #{GEM_NAME}-#{GEM_VERSION}.gem --dev"
end

task publish: :build do
  system "gem push #{GEM_NAME}-#{GEM_VERSION}.gem"
end

task :clean do
  system 'rm *.gem'
end

RSpec::Core::RakeTask.new(:test) do |task|
  root_dir = Rake.application.original_dir
  task.pattern = "#{root_dir}/spec/*_spec.rb"
  task.verbose = false
end

task test: :devinstall
task test_refreshed_data: [:devinstall, 'test-data']
