# frozen_string_literal: true

require "bundler/gem_tasks"
require_relative 'lib/eppo_client/version'

GEM_NAME = 'eppo-server-sdk'
GEM_VERSION = EppoClient::VERSION

require "rb_sys/extensiontask"

task default: :build

GEMSPEC = Gem::Specification.load("eppo-server-sdk.gemspec")

RbSys::ExtensionTask.new("eppo_client", GEMSPEC) do |ext|
  ext.lib_dir = "lib/eppo_client"

  ext.cross_compile = true
end

task build: :compile do
  system "gem build #{GEM_NAME}.gemspec"
end

task install: :build do
  system "gem install #{GEM_NAME}-#{GEM_VERSION}.gem"
end

task devinstall: :build do
  system "gem install #{GEM_NAME}-#{GEM_VERSION}.gem --dev"
end

task publish: :build do
  system "gem push #{GEM_NAME}-#{GEM_VERSION}.gem"
end

task :clean do
  system 'rm *.gem'
end

task test: :devinstall
task test_refreshed_data: [:devinstall, 'test-data']
